"""call meta

Revision ID: c9f8166ba2d1
Revises: c982ce96e5cc
Create Date: 2020-06-20 15:39:29.429255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f8166ba2d1'
down_revision = 'c982ce96e5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('call_time', sa.DateTime(), nullable=False))
    op.add_column('call', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('call', sa.Column('result', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'result')
    op.drop_column('call', 'rate')
    op.drop_column('call', 'call_time')
    # ### end Alembic commands ###
