"""timestamp to call_time

Revision ID: 434e84c45a4d
Revises: 39d762224aeb
Create Date: 2020-06-20 22:06:05.871117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '434e84c45a4d'
down_revision = '39d762224aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('call_time', sa.DateTime(), nullable=False))
    op.drop_column('call', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('timestamp', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('call', 'call_time')
    # ### end Alembic commands ###
