"""time_table_timefix

Revision ID: 601a6bd3150e
Revises: 283d53b12d7d
Create Date: 2020-06-20 15:51:51.443833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601a6bd3150e'
down_revision = 'c9f8166ba2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import mssql
    op.drop_column('time_table', 'start_work')
    op.drop_column('time_table', 'end_work')
    op.add_column('time_table',
                  sa.Column('start_work', sa.Time, nullable=False))
    op.add_column('time_table',
                  sa.Column('end_work', sa.Time, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_table', 'start_work')
    op.drop_column('time_table', 'end_work')
    op.add_column('time_table',
                  sa.Column('start_work', sa.DateTime, nullable=False))
    op.add_column('time_table',
                  sa.Column('end_work', sa.DateTime, nullable=False))
    # ### end Alembic commands ###
