"""remove timezone

Revision ID: 2ffa31f4aaf2
Revises: 434e84c45a4d
Create Date: 2020-06-20 22:14:55.796887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ffa31f4aaf2'
down_revision = '434e84c45a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'timezone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('timezone', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
