"""community manager admin

Revision ID: d5d1163f33a3
Revises: b7197871dd7a
Create Date: 2020-06-19 20:21:02.917347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d1163f33a3'
down_revision = 'b7197871dd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('community_vk_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_admins',
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('community_managers',
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_managers')
    op.drop_table('community_admins')
    op.drop_table('manager')
    op.drop_table('community')
    # ### end Alembic commands ###
