"""call time fix

Revision ID: 4cdcfe01dfa2
Revises: 2ffa31f4aaf2
Create Date: 2020-06-20 22:19:06.485881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import mysql

revision = '4cdcfe01dfa2'
down_revision = '2ffa31f4aaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'call_time')
    op.add_column('call', sa.Column('call_time', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'call_time')
    op.add_column('call', sa.Column('timestamp', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
