"""call_timestamp

Revision ID: 39d762224aeb
Revises: 601a6bd3150e
Create Date: 2020-06-20 19:35:00.007835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d762224aeb'
down_revision = '601a6bd3150e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'call_time')
    op.add_column('call', sa.Column('timestamp', sa.String(length=100), nullable=False))
    op.add_column('call', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('manager', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'timestamp')
    op.add_column('call', sa.Column('call_time', sa.DateTime(), nullable=False))
    op.drop_column('manager', 'timezone')
    op.drop_column('call', 'timezone')
    # ### end Alembic commands ###
