"""time_table

Revision ID: fbc121875bdb
Revises: 051b400f7f55
Create Date: 2020-06-20 11:40:31.042458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc121875bdb'
down_revision = '051b400f7f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_table',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_the_week', sa.String(length=10), nullable=False),
    sa.Column('start_work', sa.DateTime(), nullable=False),
    sa.Column('end_work', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_table')
    # ### end Alembic commands ###
