"""api key

Revision ID: c982ce96e5cc
Revises: 283d53b12d7d
Create Date: 2020-06-20 15:35:12.678577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c982ce96e5cc'
down_revision = '283d53b12d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('api_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'api_key')
    # ### end Alembic commands ###
